Let `muladd` accept arrays
JuliaLang/Compat.jl pull request #729
Opened 2020-10-29 13:57 UTC by mcabbott

This adds https://github.com/JuliaLang/julia/pull/37065

2020-10-29 15:26 UTC, simeonschaub commented
Don't we have a 5-arg `mul!` in Compat now? Couldn't we just use that for compatibility with all older versions?

2020-10-29 15:47 UTC, mcabbott commented
Yes we do, and I guess this uses it on early enough versions. But test failures earlier were from recursive dot issues.

2020-10-29 15:52 UTC, simeonschaub commented
Ah, I see!

2020-11-02 10:11 UTC, martinholters commented on test/runtests.jl
> +    end
If it's just about the RHS, could work around that:
```suggestion
    if VERSION >= v"1.5"
        # Julia 1.4 gets vofm' * vofm wrong, gives a scalar
        @test muladd(vofm', vofm, vofm[1]) == vofm' * vofm .+ vofm[1] # inner
    else
        @test muladd(vofm', vofm, vofm[1]) == only(convert(Matrix, vofm') * vofm) .+ vofm[1] # inner
    end
```

2020-11-02 11:31 UTC, mcabbott commented on test/runtests.jl
> +    end
Yes that's probably better. 

PR is paused BTW as, after the one to Base got merged, we discovered that `muladd` wasn't only in use for scalars as I thought, so the methods being added for arrays ought to be more careful. Will update once its correction is in.

2020-11-20 10:40 UTC, mcabbott commented
Test failure on MacOS nightly looks to be that it has a too-old nightly, it passes locally.

It might be possible to make the definitions here work on nightly versions between the two PRs above, but won't be easy to avoid ambiguities, and that doesn't seem like a great use of time.

2020-11-28 13:19 UTC, mcabbott commented
(Sorry about the noise! Trying to re-trigger travis.)

2020-12-17 11:48 UTC, mcabbott commented
Bump? CI looks happy, tests pass locally on 1.3, 1.4, 1.5.

2021-01-11 13:43 UTC, oxinabox commented
Bump

2021-01-11 15:06 UTC, omus requested changes

2021-01-11 15:06 UTC, omus commented on test/runtests.jl
> +    end
Missing the `muladd(v3', v3, [1])` test from the original PR.

2021-01-11 15:08 UTC, omus commented on test/runtests.jl
> +    end
Oh, this was dropped from the second PR

2021-01-11 15:09 UTC, omus commented on test/runtests.jl
> +        @test_throws DimensionMismatch muladd(u2', u2, [1,1]) == [dot(u2,u2) + 1]
Looks to be a mistake that also exists in https://github.com/JuliaLang/julia/pull/38250 so this can be left in.

2021-01-11 15:09 UTC, omus commented on test/runtests.jl
> +    A23 = reshape(1:6, 2,3) .+ 0
Also in https://github.com/JuliaLang/julia/pull/38250 so we can leave this

2021-01-11 15:12 UTC, omus commented on test/runtests.jl
> +
Just for consistency
```suggestion
end

@testset "muladd & structured matrices" begin
```

2021-01-22 12:46 UTC, mcabbott commented on test/runtests.jl
> +    A23 = reshape(1:6, 2,3) .+ 0
Yes maybe not optimal style, it rhymes with the `.+ im` is probably what I was thinking.

2021-01-22 12:47 UTC, mcabbott commented on test/runtests.jl
> +        @test_throws DimensionMismatch muladd(u2', u2, [1,1]) == [dot(u2,u2) + 1]
Oh right, my mistake, I don't remember how that happened.

2021-01-22 12:51 UTC, mcabbott commented on test/runtests.jl
> +
Here I think the logic was that it's a bit neater if the whole PR is one testset, since all the others are, and all have comments about what Julia PRs they follow. Could be done more elaborate ways. Or divided up if this strikes you as very weird. Maybe with a comment saying "# continuted..." or something.

2021-01-22 12:51 UTC, mcabbott commented on README.md
> +>>>>>>> readme + version
Sorry!

2021-02-28 19:50 UTC, omus commented on test/runtests.jl
> +
I think either option is fine. It's just seems like a mistake that this was commented out without comment

2021-04-27 08:00 UTC, simeonschaub commented on README.md
> +[#37065]: https://github.com/JuliaLang/julia/pull/37065
```suggestion
```

2021-04-27 08:01 UTC, simeonschaub approved these changes
LGTM

2021-04-27 08:15 UTC, martinholters commented on test/runtests.jl
> +
Agree. The current status looks a bit strange.

2021-04-27 13:17 UTC, mcabbott commented on test/runtests.jl
> +    # @testset "muladd & structured matrices" begin
```suggestion
    # muladd & structured matrices
```

2021-05-18 13:49 UTC, omus approved these changes
Will merge after CI passes

2021-05-18 14:00 UTC, merged