Support `round`/`trunc`/`ceil`/`floor` for `Bool`
JuliaLang/Compat.jl pull request #799
Opened 2023-06-21 16:12 UTC by mtfishman

Closes #798.

2023-06-22 05:33 UTC, martinholters requested changes
Basically lgtm, but needs an entry in the README. Also feel free to bump the version in Project.toml for an immediate release.

2023-06-22 05:33 UTC, martinholters commented on src/Compat.jl
> +if VERSION < v"1.8.0-beta2.17"
Strictly speaking, this should probably be:
```suggestion
if VERSION < v"1.8.0-beta2.17" || v"1.9.0-" <= VERSION < v"1.9.0-DEV.94
```
I doubt that'll make any difference in practice, though.

2023-06-22 14:11 UTC, mtfishman commented
@martinholters I added an entry to the README and bumped the version, good from my end.

2023-06-23 05:53 UTC, martinholters approved these changes

2023-06-23 05:54 UTC, merged